import {
  AccessibilityIcon,
  ActivityLogIcon,
  AlignBaselineIcon,
  AlignBottomIcon,
  AlignCenterHorizontallyIcon,
  AlignCenterVerticallyIcon,
  AlignLeftIcon,
  AlignRightIcon,
  AlignTopIcon,
  AllSidesIcon,
  AngleIcon,
  ArchiveIcon,
  ArrowBottomLeftIcon,
  ArrowBottomRightIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowTopLeftIcon,
  ArrowTopRightIcon,
  ArrowUpIcon,
  AspectRatioIcon,
  AvatarIcon,
  BackpackIcon,
  BadgeIcon,
  BarChartIcon,
  BellIcon,
  BlendingModeIcon,
  BookmarkIcon,
  BookmarkFilledIcon,
  BorderAllIcon,
  BorderBottomIcon,
  BorderDashedIcon,
  BorderDottedIcon,
  BorderLeftIcon,
  BorderNoneIcon,
  BorderRightIcon,
  BorderSolidIcon,
  BorderSplitIcon,
  BorderStyleIcon,
  BorderTopIcon,
  BorderWidthIcon,
  BoxIcon,
  BoxModelIcon,
  ButtonIcon,
  CalendarIcon,
  CameraIcon,
  CardStackIcon,
  CardStackMinusIcon,
  CardStackPlusIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CaretSortIcon,
  CaretUpIcon,
  ChatBubbleIcon,
  CheckIcon,
  CheckCircledIcon,
  CheckboxIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CircleIcon,
  CircleBackslashIcon,
  ClipboardIcon,
  ClipboardCopyIcon,
  ClockIcon,
  CodeIcon,
  CodeSandboxLogoIcon,
  ColorWheelIcon,
  ColumnSpacingIcon,
  ColumnsIcon,
  CommitIcon,
  Component1Icon,
  Component2Icon,
  ComponentBooleanIcon,
  ComponentInstanceIcon,
  ComponentNoneIcon,
  ComponentPlaceholderIcon,
  ContainerIcon,
  CookieIcon,
  CopyIcon,
  CornerBottomLeftIcon,
  CornerBottomRightIcon,
  CornerTopLeftIcon,
  CornerTopRightIcon,
  CornersIcon,
  CountdownTimerIcon,
  CounterClockwiseClockIcon,
  CropIcon,
  Cross1Icon,
  Cross2Icon,
  CrossCircledIcon,
  Crosshair1Icon,
  Crosshair2Icon,
  CrumpledPaperIcon,
  CubeIcon,
  CursorArrowIcon,
  CursorTextIcon,
  DashIcon,
  DashboardIcon,
  DesktopIcon,
  DimensionsIcon,
  DiscIcon,
  DiscordLogoIcon,
  DividerHorizontalIcon,
  DividerVerticalIcon,
  DotIcon,
  DotFilledIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DoubleArrowDownIcon,
  DoubleArrowLeftIcon,
  DoubleArrowRightIcon,
  DoubleArrowUpIcon,
  DownloadIcon,
  DragHandleDots1Icon,
  DragHandleDots2Icon,
  DragHandleHorizontalIcon,
  DragHandleVerticalIcon,
  DrawingPinIcon,
  DrawingPinFilledIcon,
  DropdownMenuIcon,
  EnterIcon,
  EnterFullScreenIcon,
  EnvelopeClosedIcon,
  EnvelopeOpenIcon,
  EraserIcon,
  ExclamationTriangleIcon,
  ExitIcon,
  ExitFullScreenIcon,
  ExternalLinkIcon,
  EyeClosedIcon,
  EyeNoneIcon,
  EyeOpenIcon,
  FaceIcon,
  FigmaLogoIcon,
  FileIcon,
  FileMinusIcon,
  FilePlusIcon,
  FileTextIcon,
  FontBoldIcon,
  FontFamilyIcon,
  FontItalicIcon,
  FontRomanIcon,
  FontSizeIcon,
  FontStyleIcon,
  FrameIcon,
  FramerLogoIcon,
  GearIcon,
  GitHubLogoIcon,
  GlobeIcon,
  GridIcon,
  GroupIcon,
  Half1Icon,
  Half2Icon,
  HamburgerMenuIcon,
  HandIcon,
  HeadingIcon,
  HeartIcon,
  HeartFilledIcon,
  HeightIcon,
  HobbyKnifeIcon,
  HomeIcon,
  IconJarLogoIcon,
  IdCardIcon,
  ImageIcon,
  InfoCircledIcon,
  InputIcon,
  InstagramLogoIcon,
  KeyboardIcon,
  LapTimerIcon,
  LaptopIcon,
  LayersIcon,
  LayoutIcon,
  LetterCaseCapitalizeIcon,
  LetterCaseLowercaseIcon,
  LetterCaseToggleIcon,
  LetterCaseUppercaseIcon,
  LetterSpacingIcon,
  LightningBoltIcon,
  LineHeightIcon,
  Link1Icon,
  Link2Icon,
  LinkBreak1Icon,
  LinkBreak2Icon,
  LinkNone1Icon,
  LinkNone2Icon,
  LinkedInLogoIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpen1Icon,
  LockOpen2Icon,
  LoopIcon,
  MagicWandIcon,
  MagnifyingGlassIcon,
  MarginIcon,
  MaskOffIcon,
  MaskOnIcon,
  MinusIcon,
  MinusCircledIcon,
  MixIcon,
  MixerHorizontalIcon,
  MixerVerticalIcon,
  MobileIcon,
  ModulzLogoIcon,
  MoonIcon,
  MoveIcon,
  NotionLogoIcon,
  OpacityIcon,
  OpenInNewWindowIcon,
  OverlineIcon,
  PaddingIcon,
  PaperPlaneIcon,
  PauseIcon,
  Pencil1Icon,
  Pencil2Icon,
  PersonIcon,
  PieChartIcon,
  PilcrowIcon,
  PinBottomIcon,
  PinLeftIcon,
  PinRightIcon,
  PinTopIcon,
  PlayIcon,
  PlusIcon,
  PlusCircledIcon,
  QuestionMarkIcon,
  QuestionMarkCircledIcon,
  QuoteIcon,
  RadiobuttonIcon,
  ReaderIcon,
  ReloadIcon,
  ResetIcon,
  ResumeIcon,
  RocketIcon,
  RotateCounterClockwiseIcon,
  RowSpacingIcon,
  RowsIcon,
  RulerHorizontalIcon,
  RulerSquareIcon,
  ScissorsIcon,
  SectionIcon,
  SewingPinIcon,
  SewingPinFilledIcon,
  ShadowIcon,
  ShadowInnerIcon,
  ShadowNoneIcon,
  ShadowOuterIcon,
  Share1Icon,
  Share2Icon,
  ShuffleIcon,
  SizeIcon,
  SketchLogoIcon,
  SlashIcon,
  SliderIcon,
  SpaceBetweenHorizontallyIcon,
  SpaceBetweenVerticallyIcon,
  SpaceEvenlyHorizontallyIcon,
  SpaceEvenlyVerticallyIcon,
  SpeakerLoudIcon,
  SpeakerModerateIcon,
  SpeakerOffIcon,
  SpeakerQuietIcon,
  SquareIcon,
  StackIcon,
  StarIcon,
  StarFilledIcon,
  StitchesLogoIcon,
  StopIcon,
  StopwatchIcon,
  StretchHorizontallyIcon,
  StretchVerticallyIcon,
  StrikethroughIcon,
  SunIcon,
  SwitchIcon,
  SymbolIcon,
  TableIcon,
  TargetIcon,
  TextIcon,
  TextAlignBottomIcon,
  TextAlignCenterIcon,
  TextAlignJustifyIcon,
  TextAlignLeftIcon,
  TextAlignMiddleIcon,
  TextAlignRightIcon,
  TextAlignTopIcon,
  TextNoneIcon,
  ThickArrowDownIcon,
  ThickArrowLeftIcon,
  ThickArrowRightIcon,
  ThickArrowUpIcon,
  TimerIcon,
  TokensIcon,
  TrackNextIcon,
  TrackPreviousIcon,
  TransformIcon,
  TransparencyGridIcon,
  TrashIcon,
  TriangleDownIcon,
  TriangleLeftIcon,
  TriangleRightIcon,
  TriangleUpIcon,
  TwitterLogoIcon,
  UnderlineIcon,
  UpdateIcon,
  UploadIcon,
  ValueIcon,
  ValueNoneIcon,
  VercelLogoIcon,
  VideoIcon,
  ViewGridIcon,
  ViewHorizontalIcon,
  ViewNoneIcon,
  ViewVerticalIcon,
  WidthIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "./index";

export const ICONS = [
  {
    slug: "accessibility-icon",
    name: "Accessibility Icon",
    component: AccessibilityIcon,
  },
  {
    slug: "activity-log-icon",
    name: "Activity Log Icon",
    component: ActivityLogIcon,
  },
  {
    slug: "align-baseline-icon",
    name: "Align Baseline Icon",
    component: AlignBaselineIcon,
  },
  {
    slug: "align-bottom-icon",
    name: "Align Bottom Icon",
    component: AlignBottomIcon,
  },
  {
    slug: "align-center-horizontally-icon",
    name: "Align Center Horizontally Icon",
    component: AlignCenterHorizontallyIcon,
  },
  {
    slug: "align-center-vertically-icon",
    name: "Align Center Vertically Icon",
    component: AlignCenterVerticallyIcon,
  },
  {
    slug: "align-left-icon",
    name: "Align Left Icon",
    component: AlignLeftIcon,
  },
  {
    slug: "align-right-icon",
    name: "Align Right Icon",
    component: AlignRightIcon,
  },
  { slug: "align-top-icon", name: "Align Top Icon", component: AlignTopIcon },
  { slug: "all-sides-icon", name: "All Sides Icon", component: AllSidesIcon },
  { slug: "angle-icon", name: "Angle Icon", component: AngleIcon },
  { slug: "archive-icon", name: "Archive Icon", component: ArchiveIcon },
  {
    slug: "arrow-bottom-left-icon",
    name: "Arrow Bottom Left Icon",
    component: ArrowBottomLeftIcon,
  },
  {
    slug: "arrow-bottom-right-icon",
    name: "Arrow Bottom Right Icon",
    component: ArrowBottomRightIcon,
  },
  {
    slug: "arrow-down-icon",
    name: "Arrow Down Icon",
    component: ArrowDownIcon,
  },
  {
    slug: "arrow-left-icon",
    name: "Arrow Left Icon",
    component: ArrowLeftIcon,
  },
  {
    slug: "arrow-right-icon",
    name: "Arrow Right Icon",
    component: ArrowRightIcon,
  },
  {
    slug: "arrow-top-left-icon",
    name: "Arrow Top Left Icon",
    component: ArrowTopLeftIcon,
  },
  {
    slug: "arrow-top-right-icon",
    name: "Arrow Top Right Icon",
    component: ArrowTopRightIcon,
  },
  { slug: "arrow-up-icon", name: "Arrow Up Icon", component: ArrowUpIcon },
  {
    slug: "aspect-ratio-icon",
    name: "Aspect Ratio Icon",
    component: AspectRatioIcon,
  },
  { slug: "avatar-icon", name: "Avatar Icon", component: AvatarIcon },
  { slug: "backpack-icon", name: "Backpack Icon", component: BackpackIcon },
  { slug: "badge-icon", name: "Badge Icon", component: BadgeIcon },
  { slug: "bar-chart-icon", name: "Bar Chart Icon", component: BarChartIcon },
  { slug: "bell-icon", name: "Bell Icon", component: BellIcon },
  {
    slug: "blending-mode-icon",
    name: "Blending Mode Icon",
    component: BlendingModeIcon,
  },
  { slug: "bookmark-icon", name: "Bookmark Icon", component: BookmarkIcon },
  {
    slug: "bookmark-filled-icon",
    name: "Bookmark Filled Icon",
    component: BookmarkFilledIcon,
  },
  {
    slug: "border-all-icon",
    name: "Border All Icon",
    component: BorderAllIcon,
  },
  {
    slug: "border-bottom-icon",
    name: "Border Bottom Icon",
    component: BorderBottomIcon,
  },
  {
    slug: "border-dashed-icon",
    name: "Border Dashed Icon",
    component: BorderDashedIcon,
  },
  {
    slug: "border-dotted-icon",
    name: "Border Dotted Icon",
    component: BorderDottedIcon,
  },
  {
    slug: "border-left-icon",
    name: "Border Left Icon",
    component: BorderLeftIcon,
  },
  {
    slug: "border-none-icon",
    name: "Border None Icon",
    component: BorderNoneIcon,
  },
  {
    slug: "border-right-icon",
    name: "Border Right Icon",
    component: BorderRightIcon,
  },
  {
    slug: "border-solid-icon",
    name: "Border Solid Icon",
    component: BorderSolidIcon,
  },
  {
    slug: "border-split-icon",
    name: "Border Split Icon",
    component: BorderSplitIcon,
  },
  {
    slug: "border-style-icon",
    name: "Border Style Icon",
    component: BorderStyleIcon,
  },
  {
    slug: "border-top-icon",
    name: "Border Top Icon",
    component: BorderTopIcon,
  },
  {
    slug: "border-width-icon",
    name: "Border Width Icon",
    component: BorderWidthIcon,
  },
  { slug: "box-icon", name: "Box Icon", component: BoxIcon },
  { slug: "box-model-icon", name: "Box Model Icon", component: BoxModelIcon },
  { slug: "button-icon", name: "Button Icon", component: ButtonIcon },
  { slug: "calendar-icon", name: "Calendar Icon", component: CalendarIcon },
  { slug: "camera-icon", name: "Camera Icon", component: CameraIcon },
  {
    slug: "card-stack-icon",
    name: "Card Stack Icon",
    component: CardStackIcon,
  },
  {
    slug: "card-stack-minus-icon",
    name: "Card Stack Minus Icon",
    component: CardStackMinusIcon,
  },
  {
    slug: "card-stack-plus-icon",
    name: "Card Stack Plus Icon",
    component: CardStackPlusIcon,
  },
  {
    slug: "caret-down-icon",
    name: "Caret Down Icon",
    component: CaretDownIcon,
  },
  {
    slug: "caret-left-icon",
    name: "Caret Left Icon",
    component: CaretLeftIcon,
  },
  {
    slug: "caret-right-icon",
    name: "Caret Right Icon",
    component: CaretRightIcon,
  },
  {
    slug: "caret-sort-icon",
    name: "Caret Sort Icon",
    component: CaretSortIcon,
  },
  { slug: "caret-up-icon", name: "Caret Up Icon", component: CaretUpIcon },
  {
    slug: "chat-bubble-icon",
    name: "Chat Bubble Icon",
    component: ChatBubbleIcon,
  },
  { slug: "check-icon", name: "Check Icon", component: CheckIcon },
  {
    slug: "check-circled-icon",
    name: "Check Circled Icon",
    component: CheckCircledIcon,
  },
  { slug: "checkbox-icon", name: "Checkbox Icon", component: CheckboxIcon },
  {
    slug: "chevron-down-icon",
    name: "Chevron Down Icon",
    component: ChevronDownIcon,
  },
  {
    slug: "chevron-left-icon",
    name: "Chevron Left Icon",
    component: ChevronLeftIcon,
  },
  {
    slug: "chevron-right-icon",
    name: "Chevron Right Icon",
    component: ChevronRightIcon,
  },
  {
    slug: "chevron-up-icon",
    name: "Chevron Up Icon",
    component: ChevronUpIcon,
  },
  { slug: "circle-icon", name: "Circle Icon", component: CircleIcon },
  {
    slug: "circle-backslash-icon",
    name: "Circle Backslash Icon",
    component: CircleBackslashIcon,
  },
  { slug: "clipboard-icon", name: "Clipboard Icon", component: ClipboardIcon },
  {
    slug: "clipboard-copy-icon",
    name: "Clipboard Copy Icon",
    component: ClipboardCopyIcon,
  },
  { slug: "clock-icon", name: "Clock Icon", component: ClockIcon },
  { slug: "code-icon", name: "Code Icon", component: CodeIcon },
  {
    slug: "code-sandbox-logo-icon",
    name: "Code Sandbox Logo Icon",
    component: CodeSandboxLogoIcon,
  },
  {
    slug: "color-wheel-icon",
    name: "Color Wheel Icon",
    component: ColorWheelIcon,
  },
  {
    slug: "column-spacing-icon",
    name: "Column Spacing Icon",
    component: ColumnSpacingIcon,
  },
  { slug: "columns-icon", name: "Columns Icon", component: ColumnsIcon },
  { slug: "commit-icon", name: "Commit Icon", component: CommitIcon },
  {
    slug: "component1-icon",
    name: "Component1 Icon",
    component: Component1Icon,
  },
  {
    slug: "component2-icon",
    name: "Component2 Icon",
    component: Component2Icon,
  },
  {
    slug: "component-boolean-icon",
    name: "Component Boolean Icon",
    component: ComponentBooleanIcon,
  },
  {
    slug: "component-instance-icon",
    name: "Component Instance Icon",
    component: ComponentInstanceIcon,
  },
  {
    slug: "component-none-icon",
    name: "Component None Icon",
    component: ComponentNoneIcon,
  },
  {
    slug: "component-placeholder-icon",
    name: "Component Placeholder Icon",
    component: ComponentPlaceholderIcon,
  },
  { slug: "container-icon", name: "Container Icon", component: ContainerIcon },
  { slug: "cookie-icon", name: "Cookie Icon", component: CookieIcon },
  { slug: "copy-icon", name: "Copy Icon", component: CopyIcon },
  {
    slug: "corner-bottom-left-icon",
    name: "Corner Bottom Left Icon",
    component: CornerBottomLeftIcon,
  },
  {
    slug: "corner-bottom-right-icon",
    name: "Corner Bottom Right Icon",
    component: CornerBottomRightIcon,
  },
  {
    slug: "corner-top-left-icon",
    name: "Corner Top Left Icon",
    component: CornerTopLeftIcon,
  },
  {
    slug: "corner-top-right-icon",
    name: "Corner Top Right Icon",
    component: CornerTopRightIcon,
  },
  { slug: "corners-icon", name: "Corners Icon", component: CornersIcon },
  {
    slug: "countdown-timer-icon",
    name: "Countdown Timer Icon",
    component: CountdownTimerIcon,
  },
  {
    slug: "counter-clockwise-clock-icon",
    name: "Counter Clockwise Clock Icon",
    component: CounterClockwiseClockIcon,
  },
  { slug: "crop-icon", name: "Crop Icon", component: CropIcon },
  { slug: "cross1-icon", name: "Cross1 Icon", component: Cross1Icon },
  { slug: "cross2-icon", name: "Cross2 Icon", component: Cross2Icon },
  {
    slug: "cross-circled-icon",
    name: "Cross Circled Icon",
    component: CrossCircledIcon,
  },
  {
    slug: "crosshair1-icon",
    name: "Crosshair1 Icon",
    component: Crosshair1Icon,
  },
  {
    slug: "crosshair2-icon",
    name: "Crosshair2 Icon",
    component: Crosshair2Icon,
  },
  {
    slug: "crumpled-paper-icon",
    name: "Crumpled Paper Icon",
    component: CrumpledPaperIcon,
  },
  { slug: "cube-icon", name: "Cube Icon", component: CubeIcon },
  {
    slug: "cursor-arrow-icon",
    name: "Cursor Arrow Icon",
    component: CursorArrowIcon,
  },
  {
    slug: "cursor-text-icon",
    name: "Cursor Text Icon",
    component: CursorTextIcon,
  },
  { slug: "dash-icon", name: "Dash Icon", component: DashIcon },
  { slug: "dashboard-icon", name: "Dashboard Icon", component: DashboardIcon },
  { slug: "desktop-icon", name: "Desktop Icon", component: DesktopIcon },
  {
    slug: "dimensions-icon",
    name: "Dimensions Icon",
    component: DimensionsIcon,
  },
  { slug: "disc-icon", name: "Disc Icon", component: DiscIcon },
  {
    slug: "discord-logo-icon",
    name: "Discord Logo Icon",
    component: DiscordLogoIcon,
  },
  {
    slug: "divider-horizontal-icon",
    name: "Divider Horizontal Icon",
    component: DividerHorizontalIcon,
  },
  {
    slug: "divider-vertical-icon",
    name: "Divider Vertical Icon",
    component: DividerVerticalIcon,
  },
  { slug: "dot-icon", name: "Dot Icon", component: DotIcon },
  {
    slug: "dot-filled-icon",
    name: "Dot Filled Icon",
    component: DotFilledIcon,
  },
  {
    slug: "dots-horizontal-icon",
    name: "Dots Horizontal Icon",
    component: DotsHorizontalIcon,
  },
  {
    slug: "dots-vertical-icon",
    name: "Dots Vertical Icon",
    component: DotsVerticalIcon,
  },
  {
    slug: "double-arrow-down-icon",
    name: "Double Arrow Down Icon",
    component: DoubleArrowDownIcon,
  },
  {
    slug: "double-arrow-left-icon",
    name: "Double Arrow Left Icon",
    component: DoubleArrowLeftIcon,
  },
  {
    slug: "double-arrow-right-icon",
    name: "Double Arrow Right Icon",
    component: DoubleArrowRightIcon,
  },
  {
    slug: "double-arrow-up-icon",
    name: "Double Arrow Up Icon",
    component: DoubleArrowUpIcon,
  },
  { slug: "download-icon", name: "Download Icon", component: DownloadIcon },
  {
    slug: "drag-handle-dots1-icon",
    name: "Drag Handle Dots1 Icon",
    component: DragHandleDots1Icon,
  },
  {
    slug: "drag-handle-dots2-icon",
    name: "Drag Handle Dots2 Icon",
    component: DragHandleDots2Icon,
  },
  {
    slug: "drag-handle-horizontal-icon",
    name: "Drag Handle Horizontal Icon",
    component: DragHandleHorizontalIcon,
  },
  {
    slug: "drag-handle-vertical-icon",
    name: "Drag Handle Vertical Icon",
    component: DragHandleVerticalIcon,
  },
  {
    slug: "drawing-pin-icon",
    name: "Drawing Pin Icon",
    component: DrawingPinIcon,
  },
  {
    slug: "drawing-pin-filled-icon",
    name: "Drawing Pin Filled Icon",
    component: DrawingPinFilledIcon,
  },
  {
    slug: "dropdown-menu-icon",
    name: "Dropdown Menu Icon",
    component: DropdownMenuIcon,
  },
  { slug: "enter-icon", name: "Enter Icon", component: EnterIcon },
  {
    slug: "enter-full-screen-icon",
    name: "Enter Full Screen Icon",
    component: EnterFullScreenIcon,
  },
  {
    slug: "envelope-closed-icon",
    name: "Envelope Closed Icon",
    component: EnvelopeClosedIcon,
  },
  {
    slug: "envelope-open-icon",
    name: "Envelope Open Icon",
    component: EnvelopeOpenIcon,
  },
  { slug: "eraser-icon", name: "Eraser Icon", component: EraserIcon },
  {
    slug: "exclamation-triangle-icon",
    name: "Exclamation Triangle Icon",
    component: ExclamationTriangleIcon,
  },
  { slug: "exit-icon", name: "Exit Icon", component: ExitIcon },
  {
    slug: "exit-full-screen-icon",
    name: "Exit Full Screen Icon",
    component: ExitFullScreenIcon,
  },
  {
    slug: "external-link-icon",
    name: "External Link Icon",
    component: ExternalLinkIcon,
  },
  {
    slug: "eye-closed-icon",
    name: "Eye Closed Icon",
    component: EyeClosedIcon,
  },
  { slug: "eye-none-icon", name: "Eye None Icon", component: EyeNoneIcon },
  { slug: "eye-open-icon", name: "Eye Open Icon", component: EyeOpenIcon },
  { slug: "face-icon", name: "Face Icon", component: FaceIcon },
  {
    slug: "figma-logo-icon",
    name: "Figma Logo Icon",
    component: FigmaLogoIcon,
  },
  { slug: "file-icon", name: "File Icon", component: FileIcon },
  {
    slug: "file-minus-icon",
    name: "File Minus Icon",
    component: FileMinusIcon,
  },
  { slug: "file-plus-icon", name: "File Plus Icon", component: FilePlusIcon },
  { slug: "file-text-icon", name: "File Text Icon", component: FileTextIcon },
  { slug: "font-bold-icon", name: "Font Bold Icon", component: FontBoldIcon },
  {
    slug: "font-family-icon",
    name: "Font Family Icon",
    component: FontFamilyIcon,
  },
  {
    slug: "font-italic-icon",
    name: "Font Italic Icon",
    component: FontItalicIcon,
  },
  {
    slug: "font-roman-icon",
    name: "Font Roman Icon",
    component: FontRomanIcon,
  },
  { slug: "font-size-icon", name: "Font Size Icon", component: FontSizeIcon },
  {
    slug: "font-style-icon",
    name: "Font Style Icon",
    component: FontStyleIcon,
  },
  { slug: "frame-icon", name: "Frame Icon", component: FrameIcon },
  {
    slug: "framer-logo-icon",
    name: "Framer Logo Icon",
    component: FramerLogoIcon,
  },
  { slug: "gear-icon", name: "Gear Icon", component: GearIcon },
  {
    slug: "git-hub-logo-icon",
    name: "Git Hub Logo Icon",
    component: GitHubLogoIcon,
  },
  { slug: "globe-icon", name: "Globe Icon", component: GlobeIcon },
  { slug: "grid-icon", name: "Grid Icon", component: GridIcon },
  { slug: "group-icon", name: "Group Icon", component: GroupIcon },
  { slug: "half1-icon", name: "Half1 Icon", component: Half1Icon },
  { slug: "half2-icon", name: "Half2 Icon", component: Half2Icon },
  {
    slug: "hamburger-menu-icon",
    name: "Hamburger Menu Icon",
    component: HamburgerMenuIcon,
  },
  { slug: "hand-icon", name: "Hand Icon", component: HandIcon },
  { slug: "heading-icon", name: "Heading Icon", component: HeadingIcon },
  { slug: "heart-icon", name: "Heart Icon", component: HeartIcon },
  {
    slug: "heart-filled-icon",
    name: "Heart Filled Icon",
    component: HeartFilledIcon,
  },
  { slug: "height-icon", name: "Height Icon", component: HeightIcon },
  {
    slug: "hobby-knife-icon",
    name: "Hobby Knife Icon",
    component: HobbyKnifeIcon,
  },
  { slug: "home-icon", name: "Home Icon", component: HomeIcon },
  {
    slug: "icon-jar-logo-icon",
    name: "Icon Jar Logo Icon",
    component: IconJarLogoIcon,
  },
  { slug: "id-card-icon", name: "Id Card Icon", component: IdCardIcon },
  { slug: "image-icon", name: "Image Icon", component: ImageIcon },
  {
    slug: "info-circled-icon",
    name: "Info Circled Icon",
    component: InfoCircledIcon,
  },
  { slug: "input-icon", name: "Input Icon", component: InputIcon },
  {
    slug: "instagram-logo-icon",
    name: "Instagram Logo Icon",
    component: InstagramLogoIcon,
  },
  { slug: "keyboard-icon", name: "Keyboard Icon", component: KeyboardIcon },
  { slug: "lap-timer-icon", name: "Lap Timer Icon", component: LapTimerIcon },
  { slug: "laptop-icon", name: "Laptop Icon", component: LaptopIcon },
  { slug: "layers-icon", name: "Layers Icon", component: LayersIcon },
  { slug: "layout-icon", name: "Layout Icon", component: LayoutIcon },
  {
    slug: "letter-case-capitalize-icon",
    name: "Letter Case Capitalize Icon",
    component: LetterCaseCapitalizeIcon,
  },
  {
    slug: "letter-case-lowercase-icon",
    name: "Letter Case Lowercase Icon",
    component: LetterCaseLowercaseIcon,
  },
  {
    slug: "letter-case-toggle-icon",
    name: "Letter Case Toggle Icon",
    component: LetterCaseToggleIcon,
  },
  {
    slug: "letter-case-uppercase-icon",
    name: "Letter Case Uppercase Icon",
    component: LetterCaseUppercaseIcon,
  },
  {
    slug: "letter-spacing-icon",
    name: "Letter Spacing Icon",
    component: LetterSpacingIcon,
  },
  {
    slug: "lightning-bolt-icon",
    name: "Lightning Bolt Icon",
    component: LightningBoltIcon,
  },
  {
    slug: "line-height-icon",
    name: "Line Height Icon",
    component: LineHeightIcon,
  },
  { slug: "link1-icon", name: "Link1 Icon", component: Link1Icon },
  { slug: "link2-icon", name: "Link2 Icon", component: Link2Icon },
  {
    slug: "link-break1-icon",
    name: "Link Break1 Icon",
    component: LinkBreak1Icon,
  },
  {
    slug: "link-break2-icon",
    name: "Link Break2 Icon",
    component: LinkBreak2Icon,
  },
  {
    slug: "link-none1-icon",
    name: "Link None1 Icon",
    component: LinkNone1Icon,
  },
  {
    slug: "link-none2-icon",
    name: "Link None2 Icon",
    component: LinkNone2Icon,
  },
  {
    slug: "linked-in-logo-icon",
    name: "Linked In Logo Icon",
    component: LinkedInLogoIcon,
  },
  {
    slug: "list-bullet-icon",
    name: "List Bullet Icon",
    component: ListBulletIcon,
  },
  {
    slug: "lock-closed-icon",
    name: "Lock Closed Icon",
    component: LockClosedIcon,
  },
  {
    slug: "lock-open1-icon",
    name: "Lock Open1 Icon",
    component: LockOpen1Icon,
  },
  {
    slug: "lock-open2-icon",
    name: "Lock Open2 Icon",
    component: LockOpen2Icon,
  },
  { slug: "loop-icon", name: "Loop Icon", component: LoopIcon },
  {
    slug: "magic-wand-icon",
    name: "Magic Wand Icon",
    component: MagicWandIcon,
  },
  {
    slug: "magnifying-glass-icon",
    name: "Magnifying Glass Icon",
    component: MagnifyingGlassIcon,
  },
  { slug: "margin-icon", name: "Margin Icon", component: MarginIcon },
  { slug: "mask-off-icon", name: "Mask Off Icon", component: MaskOffIcon },
  { slug: "mask-on-icon", name: "Mask On Icon", component: MaskOnIcon },
  { slug: "minus-icon", name: "Minus Icon", component: MinusIcon },
  {
    slug: "minus-circled-icon",
    name: "Minus Circled Icon",
    component: MinusCircledIcon,
  },
  { slug: "mix-icon", name: "Mix Icon", component: MixIcon },
  {
    slug: "mixer-horizontal-icon",
    name: "Mixer Horizontal Icon",
    component: MixerHorizontalIcon,
  },
  {
    slug: "mixer-vertical-icon",
    name: "Mixer Vertical Icon",
    component: MixerVerticalIcon,
  },
  { slug: "mobile-icon", name: "Mobile Icon", component: MobileIcon },
  {
    slug: "modulz-logo-icon",
    name: "Modulz Logo Icon",
    component: ModulzLogoIcon,
  },
  { slug: "moon-icon", name: "Moon Icon", component: MoonIcon },
  { slug: "move-icon", name: "Move Icon", component: MoveIcon },
  {
    slug: "notion-logo-icon",
    name: "Notion Logo Icon",
    component: NotionLogoIcon,
  },
  { slug: "opacity-icon", name: "Opacity Icon", component: OpacityIcon },
  {
    slug: "open-in-new-window-icon",
    name: "Open In New Window Icon",
    component: OpenInNewWindowIcon,
  },
  { slug: "overline-icon", name: "Overline Icon", component: OverlineIcon },
  { slug: "padding-icon", name: "Padding Icon", component: PaddingIcon },
  {
    slug: "paper-plane-icon",
    name: "Paper Plane Icon",
    component: PaperPlaneIcon,
  },
  { slug: "pause-icon", name: "Pause Icon", component: PauseIcon },
  { slug: "pencil1-icon", name: "Pencil1 Icon", component: Pencil1Icon },
  { slug: "pencil2-icon", name: "Pencil2 Icon", component: Pencil2Icon },
  { slug: "person-icon", name: "Person Icon", component: PersonIcon },
  { slug: "pie-chart-icon", name: "Pie Chart Icon", component: PieChartIcon },
  { slug: "pilcrow-icon", name: "Pilcrow Icon", component: PilcrowIcon },
  {
    slug: "pin-bottom-icon",
    name: "Pin Bottom Icon",
    component: PinBottomIcon,
  },
  { slug: "pin-left-icon", name: "Pin Left Icon", component: PinLeftIcon },
  { slug: "pin-right-icon", name: "Pin Right Icon", component: PinRightIcon },
  { slug: "pin-top-icon", name: "Pin Top Icon", component: PinTopIcon },
  { slug: "play-icon", name: "Play Icon", component: PlayIcon },
  { slug: "plus-icon", name: "Plus Icon", component: PlusIcon },
  {
    slug: "plus-circled-icon",
    name: "Plus Circled Icon",
    component: PlusCircledIcon,
  },
  {
    slug: "question-mark-icon",
    name: "Question Mark Icon",
    component: QuestionMarkIcon,
  },
  {
    slug: "question-mark-circled-icon",
    name: "Question Mark Circled Icon",
    component: QuestionMarkCircledIcon,
  },
  { slug: "quote-icon", name: "Quote Icon", component: QuoteIcon },
  {
    slug: "radiobutton-icon",
    name: "Radiobutton Icon",
    component: RadiobuttonIcon,
  },
  { slug: "reader-icon", name: "Reader Icon", component: ReaderIcon },
  { slug: "reload-icon", name: "Reload Icon", component: ReloadIcon },
  { slug: "reset-icon", name: "Reset Icon", component: ResetIcon },
  { slug: "resume-icon", name: "Resume Icon", component: ResumeIcon },
  { slug: "rocket-icon", name: "Rocket Icon", component: RocketIcon },
  {
    slug: "rotate-counter-clockwise-icon",
    name: "Rotate Counter Clockwise Icon",
    component: RotateCounterClockwiseIcon,
  },
  {
    slug: "row-spacing-icon",
    name: "Row Spacing Icon",
    component: RowSpacingIcon,
  },
  { slug: "rows-icon", name: "Rows Icon", component: RowsIcon },
  {
    slug: "ruler-horizontal-icon",
    name: "Ruler Horizontal Icon",
    component: RulerHorizontalIcon,
  },
  {
    slug: "ruler-square-icon",
    name: "Ruler Square Icon",
    component: RulerSquareIcon,
  },
  { slug: "scissors-icon", name: "Scissors Icon", component: ScissorsIcon },
  { slug: "section-icon", name: "Section Icon", component: SectionIcon },
  {
    slug: "sewing-pin-icon",
    name: "Sewing Pin Icon",
    component: SewingPinIcon,
  },
  {
    slug: "sewing-pin-filled-icon",
    name: "Sewing Pin Filled Icon",
    component: SewingPinFilledIcon,
  },
  { slug: "shadow-icon", name: "Shadow Icon", component: ShadowIcon },
  {
    slug: "shadow-inner-icon",
    name: "Shadow Inner Icon",
    component: ShadowInnerIcon,
  },
  {
    slug: "shadow-none-icon",
    name: "Shadow None Icon",
    component: ShadowNoneIcon,
  },
  {
    slug: "shadow-outer-icon",
    name: "Shadow Outer Icon",
    component: ShadowOuterIcon,
  },
  { slug: "share1-icon", name: "Share1 Icon", component: Share1Icon },
  { slug: "share2-icon", name: "Share2 Icon", component: Share2Icon },
  { slug: "shuffle-icon", name: "Shuffle Icon", component: ShuffleIcon },
  { slug: "size-icon", name: "Size Icon", component: SizeIcon },
  {
    slug: "sketch-logo-icon",
    name: "Sketch Logo Icon",
    component: SketchLogoIcon,
  },
  { slug: "slash-icon", name: "Slash Icon", component: SlashIcon },
  { slug: "slider-icon", name: "Slider Icon", component: SliderIcon },
  {
    slug: "space-between-horizontally-icon",
    name: "Space Between Horizontally Icon",
    component: SpaceBetweenHorizontallyIcon,
  },
  {
    slug: "space-between-vertically-icon",
    name: "Space Between Vertically Icon",
    component: SpaceBetweenVerticallyIcon,
  },
  {
    slug: "space-evenly-horizontally-icon",
    name: "Space Evenly Horizontally Icon",
    component: SpaceEvenlyHorizontallyIcon,
  },
  {
    slug: "space-evenly-vertically-icon",
    name: "Space Evenly Vertically Icon",
    component: SpaceEvenlyVerticallyIcon,
  },
  {
    slug: "speaker-loud-icon",
    name: "Speaker Loud Icon",
    component: SpeakerLoudIcon,
  },
  {
    slug: "speaker-moderate-icon",
    name: "Speaker Moderate Icon",
    component: SpeakerModerateIcon,
  },
  {
    slug: "speaker-off-icon",
    name: "Speaker Off Icon",
    component: SpeakerOffIcon,
  },
  {
    slug: "speaker-quiet-icon",
    name: "Speaker Quiet Icon",
    component: SpeakerQuietIcon,
  },
  { slug: "square-icon", name: "Square Icon", component: SquareIcon },
  { slug: "stack-icon", name: "Stack Icon", component: StackIcon },
  { slug: "star-icon", name: "Star Icon", component: StarIcon },
  {
    slug: "star-filled-icon",
    name: "Star Filled Icon",
    component: StarFilledIcon,
  },
  {
    slug: "stitches-logo-icon",
    name: "Stitches Logo Icon",
    component: StitchesLogoIcon,
  },
  { slug: "stop-icon", name: "Stop Icon", component: StopIcon },
  { slug: "stopwatch-icon", name: "Stopwatch Icon", component: StopwatchIcon },
  {
    slug: "stretch-horizontally-icon",
    name: "Stretch Horizontally Icon",
    component: StretchHorizontallyIcon,
  },
  {
    slug: "stretch-vertically-icon",
    name: "Stretch Vertically Icon",
    component: StretchVerticallyIcon,
  },
  {
    slug: "strikethrough-icon",
    name: "Strikethrough Icon",
    component: StrikethroughIcon,
  },
  { slug: "sun-icon", name: "Sun Icon", component: SunIcon },
  { slug: "switch-icon", name: "Switch Icon", component: SwitchIcon },
  { slug: "symbol-icon", name: "Symbol Icon", component: SymbolIcon },
  { slug: "table-icon", name: "Table Icon", component: TableIcon },
  { slug: "target-icon", name: "Target Icon", component: TargetIcon },
  { slug: "text-icon", name: "Text Icon", component: TextIcon },
  {
    slug: "text-align-bottom-icon",
    name: "Text Align Bottom Icon",
    component: TextAlignBottomIcon,
  },
  {
    slug: "text-align-center-icon",
    name: "Text Align Center Icon",
    component: TextAlignCenterIcon,
  },
  {
    slug: "text-align-justify-icon",
    name: "Text Align Justify Icon",
    component: TextAlignJustifyIcon,
  },
  {
    slug: "text-align-left-icon",
    name: "Text Align Left Icon",
    component: TextAlignLeftIcon,
  },
  {
    slug: "text-align-middle-icon",
    name: "Text Align Middle Icon",
    component: TextAlignMiddleIcon,
  },
  {
    slug: "text-align-right-icon",
    name: "Text Align Right Icon",
    component: TextAlignRightIcon,
  },
  {
    slug: "text-align-top-icon",
    name: "Text Align Top Icon",
    component: TextAlignTopIcon,
  },
  { slug: "text-none-icon", name: "Text None Icon", component: TextNoneIcon },
  {
    slug: "thick-arrow-down-icon",
    name: "Thick Arrow Down Icon",
    component: ThickArrowDownIcon,
  },
  {
    slug: "thick-arrow-left-icon",
    name: "Thick Arrow Left Icon",
    component: ThickArrowLeftIcon,
  },
  {
    slug: "thick-arrow-right-icon",
    name: "Thick Arrow Right Icon",
    component: ThickArrowRightIcon,
  },
  {
    slug: "thick-arrow-up-icon",
    name: "Thick Arrow Up Icon",
    component: ThickArrowUpIcon,
  },
  { slug: "timer-icon", name: "Timer Icon", component: TimerIcon },
  { slug: "tokens-icon", name: "Tokens Icon", component: TokensIcon },
  {
    slug: "track-next-icon",
    name: "Track Next Icon",
    component: TrackNextIcon,
  },
  {
    slug: "track-previous-icon",
    name: "Track Previous Icon",
    component: TrackPreviousIcon,
  },
  { slug: "transform-icon", name: "Transform Icon", component: TransformIcon },
  {
    slug: "transparency-grid-icon",
    name: "Transparency Grid Icon",
    component: TransparencyGridIcon,
  },
  { slug: "trash-icon", name: "Trash Icon", component: TrashIcon },
  {
    slug: "triangle-down-icon",
    name: "Triangle Down Icon",
    component: TriangleDownIcon,
  },
  {
    slug: "triangle-left-icon",
    name: "Triangle Left Icon",
    component: TriangleLeftIcon,
  },
  {
    slug: "triangle-right-icon",
    name: "Triangle Right Icon",
    component: TriangleRightIcon,
  },
  {
    slug: "triangle-up-icon",
    name: "Triangle Up Icon",
    component: TriangleUpIcon,
  },
  {
    slug: "twitter-logo-icon",
    name: "Twitter Logo Icon",
    component: TwitterLogoIcon,
  },
  { slug: "underline-icon", name: "Underline Icon", component: UnderlineIcon },
  { slug: "update-icon", name: "Update Icon", component: UpdateIcon },
  { slug: "upload-icon", name: "Upload Icon", component: UploadIcon },
  { slug: "value-icon", name: "Value Icon", component: ValueIcon },
  {
    slug: "value-none-icon",
    name: "Value None Icon",
    component: ValueNoneIcon,
  },
  {
    slug: "vercel-logo-icon",
    name: "Vercel Logo Icon",
    component: VercelLogoIcon,
  },
  { slug: "video-icon", name: "Video Icon", component: VideoIcon },
  { slug: "view-grid-icon", name: "View Grid Icon", component: ViewGridIcon },
  {
    slug: "view-horizontal-icon",
    name: "View Horizontal Icon",
    component: ViewHorizontalIcon,
  },
  { slug: "view-none-icon", name: "View None Icon", component: ViewNoneIcon },
  {
    slug: "view-vertical-icon",
    name: "View Vertical Icon",
    component: ViewVerticalIcon,
  },
  { slug: "width-icon", name: "Width Icon", component: WidthIcon },
  { slug: "zoom-in-icon", name: "Zoom In Icon", component: ZoomInIcon },
  { slug: "zoom-out-icon", name: "Zoom Out Icon", component: ZoomOutIcon },
] as const;
