FROM node:22.9.0-bookworm AS base

WORKDIR /app

COPY package*json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

RUN corepack enable pnpm && pnpm i

COPY migrations ./migrations
COPY migrate.js ./migrate.js

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 postgre

RUN chown -R postgre:nodejs /app

USER postgre

CMD ["node", "migrate.js"]